# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'socialcalendar' do
  use_frameworks!

  # Firebase pod
  pod 'Firebase/Auth'
  pod 'FirebaseAnalytics'
end
